### ISSUE TITLE
I can't get it to go transparent and fade away

### ISSUE THREAD

**Issue by TheRagingGamer85** [Enubia/ghost-chat#760] opened 2024-01-01 01:17 UTC
I just downloaded it and I got it connected to my Restream chat, but I'm not finding how to make it transparent and fade. I set the fade to 5 seconds, but it just sits on my screen blocking my view. I can se the click through but that's it. When I set Vanish, all that happens is the border disappears and I can click through it, but the background stays there and blocks my view. I like the thought of this as I am a single screen streamer, but not at the cost of seeing my game.....

**Comment by Enubia** [comment] 2024-01-01 08:40
can you provide me a screenshot of what it looks like when you click on vanish?

**Comment by TheRagingGamer85** [comment] 2024-01-01 10:05
This
    On Monday, January 1, 2024 at 03:41:00 AM EST, Enubia ***@***.***> wrote:  
 
 


can you provide me a screenshot of what it looks like when you click on vanish?

**Comment by Enubia** [comment] 2024-01-01 10:07
> This On Monday, January 1, 2024 at 03:41:00 AM EST, Enubia ***@***.***> wrote: can you provide me a screenshot of what it looks like when you click on vanish? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

I think the image was not attached

**Comment by TheRagingGamer85** [comment] 2024-01-01 10:23
It shows as attached for me, but I will resend next time in on my PC, it is currently up for the night

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 1, 2024 at 5:07 AM, ***@***.***> wrote:   



This On Monday, January 1, 2024 at 03:41:00 AM EST, Enubia @.> wrote: can you provide me a screenshot of what it looks like when you click on vanish? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


I think the image was not attached

**Comment by Enubia** [comment] 2024-01-03 14:36
In case you still have this issue we probably found a solution

```
GhostChat shows a black window when vanish is activated
This might be caused in Dual GPU Systems due to the fact that hardware acceleration cannot decide which GPU to choose.
In this case try the following:

Navigate to System > Display > Graphics
In the app list locate GhostChat
Click on it an open Options
You should now see mulptiple GPU options
Choose one of them and set it to default
You might need to relaunch GhostChat afterwards

The black background should've now disappeared.
```

**Comment by Enubia** [comment] 2024-01-03 14:36
please let me know if this helps

**Comment by TheRagingGamer85** [comment] 2024-01-03 23:49
Ghost Chat isn't showing up in the app list, nor can I find it to add it :/
    On Wednesday, January 3, 2024 at 09:36:32 AM EST, Enubia ***@***.***> wrote:  
 
 


please let me know if this helps

**Comment by dsimonow** [comment] 2024-01-07 13:22
What do you mean you can't find it to add it? 
You open in explorer where you installed ghost-chat.
Then press in the url bar, copy that link.
Then go in and search for it by adding it and then select the Ghost Chat Exe. 
If you can't find it with the explorer then it isn't installed or generally an user error.

Hope this helps.

**Comment by TheRagingGamer85** [comment] 2024-01-08 01:30
I click search in the Graphics settings for the Display and Ghost Chat doesn't appear for an option to add it to the settings. And I know it is if fact installed as I can USE the app, I just can not get it to fade away and disappear so it's not constantly blocking my view of what I am doing, I have also noticed that Full screen applications still override the Ghost Chat app
    On Sunday, January 7, 2024 at 08:22:30 AM EST, Dimitri ***@***.***> wrote:  
 
 


What do you mean you can't find it to add it?
You open in explorer where you installed ghost-chat.
Then press in the url bar, copy that link.
Then go in and search for it by adding it and then select the Ghost Chat Exe.
If you can't find it with the explorer then it isn't installed or generally an user error.

Hope this helps.

**Comment by dsimonow** [comment] 2024-01-08 12:21
What do you mean with add it? I thought you meant the option above "Search the list" where all the Apps are listed.
Look One Section above the list which states what Custom App you want to add. There you select Desktop App and look for Ghost Chat with your explorer.

**Comment by TheRagingGamer85** [comment] 2024-01-08 18:35
So I got it added and selected one of the graphics options and it's still not fading away......I tried it with both cards and neither of them are working to allow Ghost chat to ghost.....
    On Monday, January 8, 2024 at 07:21:39 AM EST, Dimitri ***@***.***> wrote:  
 
 


What do you mean with add it? I thought you meant the option above "Search the list" where all the Apps are listed.
Look One Section above the list which states what Custom App you want to add. There you select Desktop App and look for Ghost Chat with your explorer.

**Comment by dsimonow** [comment] 2024-01-08 20:23
Under Settings -> KapChat, what do you have under Chat Theme. 
To be able to help you further, find out how to post a screenshot in here. 
With that attach screenshot of your settings and the Program with vanish on and one where it is off.

**Comment by TheRagingGamer85** [comment] 2024-01-08 20:46
the Theme is set to none right now, but I have tried switching themes, I have attached the vanish on and off images
    On Monday, January 8, 2024 at 03:24:00 PM EST, Dimitri ***@***.***> wrote:  
 
 


Under Settings -> KapChat, what do you have under Chat Theme.
To be able to help you further, find out how to post a screenshot in here.
With that attach screenshot of your settings and the Program with vanish on and one where it is off.

**Comment by Enubia** [comment] 2024-01-09 09:24
@TheRagingGamer85 please answer directly in this thread if you want to attach images, they aren't sent correctly when you reply via email, unfortunately, or I'd suggest joining the discord and we can help you there as this is an easier way to communicate

**Comment by TheRagingGamer85** [comment] 2024-01-09 09:29
I thought I WAS replying to this thread, but I agree Discord would be easier (and probably faster) can you send me an invite link to the Discord Server?
    On Tuesday, January 9, 2024 at 04:25:09 AM EST, Enubia ***@***.***> wrote:  
 
 


@TheRagingGamer85 please answer directly in this thread if you want to attach images, they aren't sent correctly when you reply via email, unfortunately, or I'd suggest joining the discord and we can help you there as this is an easier way to communicate

**Comment by Enubia** [comment] 2024-01-09 09:53
here you go [discord.gg/UVMX32dDcy](https://discord.gg/UVMX32dDcy)

yes you were answering here but images could not be attached

**Comment by Enubia** [comment] 2024-01-10 08:38
closing since it's not a bug

it's the restream site that's not transparent

**Closed by Enubia** 2024-01-10 08:38 UTC
Labels: help wanted
